### ISSUE TITLE
为啥短信登陆不上去

### ISSUE THREAD

**Issue by lds233** [ChinaTelecomOperators/ChinaUnicom#4]
〽️ 开始
↓ res status
200
↓ res body
{"filename":"","menuUrl":"","dsc":"尊敬的客户您好，请使用短信验证码登录进行身份验证!","code":"2","desmobile":"","type":""}
Error: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
    at sign (/ql/data/scripts/raw_Prerelease-Alpha_10010_sms_sign.js:3:126672)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/raw_Prerelease-Alpha_10010_sms_sign.js:3:125491

**Comment by aextzhu** [comment]
我也是这个问题，作者不更新的话看来是用不成了
